apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: jb-thesis-project
data:
  prometheus.yml: |-
    {
      "apiVersion": 1,
      "datasources": [
        {
          "access":"proxy",
          "editable": true,
          "name": "prometheus",
          "orgId": 1,
          "type": "prometheus",
          "url": "http://prometheus:80",
          "version":1
        }
      ]
    }
