apiVersion: apps/v1
kind: Deployment
metadata:
  name: identityserver-deployment
  namespace: jb-thesis-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identityserver
  template:
    metadata:
      labels:
        app: identityserver
    spec:
      containers:
      - name: identityserver
        image: studentenk8sregistry.azurecr.io/jb-thesis-identityserver:v1
        env:
        - name: ASPNETCORE_URLS
          valueFrom:
            configMapKeyRef:
              name: jb-thesis-project-configmap
              key: ASPNETCORE_URLS
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: jb-thesis-project-configmap
              key: ASPNETCORE_ENVIRONMENT
        - name: WebApp__Callback-Url
          valueFrom:
            configMapKeyRef:
              name: jb-thesis-project-configmap
              key: WebApp__Callback-Url
        - name: WebApp__Silent-Refresh-Url
          valueFrom:
            configMapKeyRef:
              name: jb-thesis-project-configmap
              key: WebApp__Silent-Refresh-Url
        - name: WebApp__Front-Channel-Logout-Url
          valueFrom:
            configMapKeyRef:
              name: jb-thesis-project-configmap
              key: WebApp__Front-Channel-Logout-Url
        - name: WebApp__Post-Logout-Redirect-Url
          valueFrom:
            configMapKeyRef:
              name: jb-thesis-project-configmap
              key: WebApp__Post-Logout-Redirect-Url
        - name: WebApp__Additional-Logout-Redirect-Url
          valueFrom:
            configMapKeyRef:
              name: jb-thesis-project-configmap
              key: WebApp__Additional-Logout-Redirect-Url
        - name: BasepathConfig__ProxyHeader
          valueFrom:
            configMapKeyRef:
              name: jb-thesis-project-configmap
              key: BasepathConfig__ProxyHeader
        - name: BasepathConfig__InternalBasePath
          valueFrom:
            configMapKeyRef:
              name: jb-thesis-project-configmap
              key: BasepathConfig__InternalBasePath
        - name: BasepathConfig__ProxyBasePath
          valueFrom:
            configMapKeyRef:
              name: jb-thesis-project-configmap
              key: BasepathConfig__ProxyBasePath
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 64Mi
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: identityserver
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: identityserver