apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-proxy-yarp-config
  namespace: jb-thesis-project
data:
  appsettings.json: |-
    {
      "ML.Proxy": {
        "Routes": {
          "weatherApi": {
            "ClusterId": "weatherCluster",
            "Match": {
              "Path": "/weatherdata/{*any}"
            },
            "Transforms": [
              { "PathRemovePrefix": "/weatherdata" }
            ]
          },
          "locationApi": {
            "ClusterId": "locationCluster",
            "Match": {
              "Path": "/locationdata/{*any}"
            },
            "Transforms": [
              { "PathRemovePrefix": "/locationdata" }
            ]
          },
          "identityServer": {
            "ClusterId": "identityCluster",
            "Match": {
              "Path": "/identity/{*any}"
            },
            "Transforms": [
              { "PathRemovePrefix": "/identity" }
            ]
          }
        },
        "Clusters": {
          "weatherCluster": {
            "Destinations": {
              "weatherApi": {
                "Address": "http://weatherapi"
              }
            }
          },
          "locationCluster": {
            "Destinations": {
              "locationApi": {
                "Address": "http://locationapi"
              }
            }
          },
          "identityCluster": {
            "Destinations": {
              "identityServer": {
                "Address": "http://identityserver"
              }
            }
          }
        }
      }
    }
