apiVersion: v1
kind: ConfigMap
metadata:
  name: jb-thesis-project-configmap
  namespace: jb-thesis-project
data:
  ASPNETCORE_URLS: http://+
  ASPNETCORE_ENVIRONMENT: Kubernetes
  IdentityServer__Authority: http://identityserver
  IdentityServer__ValidIssuers__0: https://jb-thesisproject.ddns.net/identity
  IdentityServer__ValidIssuers__1: http://identityserver
  IdentityServer__RequireHttpsMetadata: "false"
  WebApp__Callback-Url: https://jb-thesisproject.ddns.net/
  WebApp__Silent-Refresh-Url: https://jb-thesisproject.ddns.net/silent-renew.html
  WebApp__Front-Channel-Logout-Url: https://jb-thesisproject.ddns.net/
  WebApp__Post-Logout-Redirect-Url: https://jb-thesisproject.ddns.net/
  WebApp__Additional-Logout-Redirect-Url: https://jb-thesisproject.ddns.net/unauthorized
  BasepathConfig__ProxyHeader: X-Forwarded-For
  BasepathConfig__InternalBasePath: /
  BasepathConfig__ProxyBasePath: /identity
  ML.Proxy.ML-Modell__ZIP__GoldenEye__Model-Path: https://github.com/JulianHBuecher/Bachelor-Thesis/raw/main/ML.Proxy.ModelTrainer/MLModelle/ZIP/GoldenEyeTrafficData-classification.zip
  ML.Proxy.ML-Modell__ZIP__LOIC__Model-Path: https://github.com/JulianHBuecher/Bachelor-Thesis/raw/main/ML.Proxy.ModelTrainer/MLModelle/ZIP/LOICTrafficData-classification.zip
  ML.Proxy.ML-Modell__ZIP__Slowloris__Model-Path: https://github.com/JulianHBuecher/Bachelor-Thesis/raw/main/ML.Proxy.ModelTrainer/MLModelle/ZIP/SlowlorisTrafficData-classification.zip
  ML.Proxy.ML-Modell__ONNX__GoldenEye__Model-Path: https://github.com/JulianHBuecher/Bachelor-Thesis/raw/main/ML.Proxy.ModelTrainer/MLModelle/ONNX/GoldenEyeTrafficData-classification.onnx
  ML.Proxy.ML-Modell__ONNX__LOIC__Model-Path: https://github.com/JulianHBuecher/Bachelor-Thesis/raw/main/ML.Proxy.ModelTrainer/MLModelle/ONNX/LOICTrafficData-classification.onnx
  ML.Proxy.ML-Modell__ONNX__Slowloris__Model-Path: https://github.com/JulianHBuecher/Bachelor-Thesis/raw/main/ML.Proxy.ModelTrainer/MLModelle/ONNX/SlowlorisTrafficData-classification.onnx
  ML.Proxy.ML-Modell__Optimized__GoldenEye__Model-Path: https://github.com/JulianHBuecher/Bachelor-Thesis/raw/main/ML.Proxy.ModelTrainer/MLModelle/Optimized/GoldenEyeTrafficData-classification.zip
  ML.Proxy.ML-Modell__Optimized__LOIC__Model-Path: https://github.com/JulianHBuecher/Bachelor-Thesis/raw/main/ML.Proxy.ModelTrainer/MLModelle/Optimized/LOICTrafficData-classification.zip
  ML.Proxy.ML-Modell__Optimized__Slowloris__Model-Path: https://github.com/JulianHBuecher/Bachelor-Thesis/raw/main/ML.Proxy.ModelTrainer/MLModelle/Optimized/SlowlorisTrafficData-classification.zip
  Serilog__MinimumLevel__Default: Information
  Serilog__MinimumLevel__Override__Microsoft: Warning
  Serilog__MinimumLevel__Override__System: Warning
  Serilog__Using__0: Serilog.Sinks.Console
  Serilog__WriteTo__0__Args__outputTemplate: "[{Timestamp:HH:mm:ss.ms} {Level:u3}] {ThreadId} {MachineName} {EnvironmentUserName} {Message:lj} <s:{SourceContext}>{NewLine}{Exception}"
  Serilog__WriteTo__0__Name: Console
  Serilog__WriteTo__1__Args__indexFormat: logstash-{0:yyyy.MM.dd}
  Serilog__WriteTo__1__Args__nodeUris: http://elasticsearch:9200
  Serilog__WriteTo__1__Name: Elasticsearch
  Serilog__WriteTo__1__Options__0__AutoRegisterTemplate: "true"
  # Redis__Connection-String: redis-requestcache:6379
  Redis__Connection-String: redis-requestcache


