apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: jb-thesis-project
data:
  redis.conf: |-
    port 6379
    protected-mode yes
    tcp-keepalive 300
    loglevel verbose
    logfile ""
    always-show-logo yes
    appendonly yes
