{
 "title": "ASP.NET Core - Controller Summary",
 "description": "Basic measurements of request handling using data from prometheus-net middleware",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instances",
    "label": "Instances",
    "query": {
     "query": "label_values(http_requests_received_total, instance)"
    }
   },
   {
    "name": "controllers",
    "label": "Controllers",
    "query": {
     "query": "label_values(http_requests_received_total{instance =~ \"$instances\"}, controller)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests received by controller",
   "type": "graph",
   "description": "Counts all requests, both successful and failed",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{instance =~ \"$instances\", controller =~ \"$controllers\"}[3m])) by (controller)",
     "legendFormat": "{{controller}}"
    },
    {
     "expr": "sum(rate(http_requests_received_total{instance =~ \"$instances\", controller = \"\"}[3m]))",
     "legendFormat": "(None)"
    }
   ]
  },
  {
   "title": "Total req/s",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "format": "reqps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{instance =~ \"$instances\", controller =~ \"$controllers\"}[3m]))"
    }
   ]
  },
  {
   "title": "In progress (global)",
   "type": "singlestat",
   "description": "Across ALL controllers globally!",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(http_requests_in_progress{instance =~ \"$instances\"})"
    }
   ]
  },
  {
   "title": "Request duration (controller-handled requests only)",
   "type": "heatmap",
   "description": "Does NOT include requests that were not mapped to an ASP.NET Core controller!",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 4 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket{instance =~ \"$instances\", controller =~ \"$controllers\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Error rate by controller",
   "type": "graph",
   "description": "4xx and 5xx status codes",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{instance =~ \"$instances\", controller =~ \"$controllers\", code =~ \"5\\\\d\\\\d|4\\\\d\\\\d\"}[3m])) by (controller)",
     "legendFormat": "{{controller}}"
    },
    {
     "expr": "sum(rate(http_requests_received_total{instance =~ \"$instances\", controller = \"\", code =~ \"5\\\\d\\\\d|4\\\\d\\\\d\"}[3m])) by (controller)",
     "legendFormat": "(None)"
    }
   ]
  }
 ]
}