{
 "title": "prometheus-net",
 "tags": [
  "prometheus-net",
  "net",
  "prometheus",
  ".net",
  ".net core"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "instances",
    "label": "instances",
    "query": {
     "query": "label_values(http_requests_received_total, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Request Related Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "The duration of HTTP requests (Location-API)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{job=\"locationapi-metrics\"}[$interval]) / rate(http_request_duration_seconds_count{job=\"locationapi-metrics\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "The duration of HTTP requests (Weather-API)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{job=\"weatherapi-metrics\"}[$interval]) / rate(http_request_duration_seconds_count{job=\"weatherapi-metrics\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "The duration of HTTP requests (IdentityServer-API)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{job=\"identityserver-metrics\"}[$interval]) / rate(http_request_duration_seconds_count{job=\"identityserver-metrics\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Technical Data of underlying system",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC collection count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(dotnet_collection_count_total[$interval])",
       "legendFormat": "Generation-{{generation}}"
      }
     ]
    },
    {
     "title": "Requests currently in progress",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "http_requests_in_progress", "legendFormat": "{{job}}" }
     ]
    },
    {
     "title": "Start time of the process",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 14, "y": 8 },
     "format": "dateTimeAsIso",
     "valueName": "current",
     "targets": [
      {
       "expr": "process_start_time_seconds{instance =~ \"$instances\"} * 1000"
      }
     ]
    },
    {
     "title": "Total known allocated memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 8, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dotnet_total_memory_bytes /1024/1024",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Total number of threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "process_num_threads", "legendFormat": "{{job}}" }
     ]
    },
    {
     "title": "Number of open handles",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "process_open_handles", "legendFormat": "{{job}}" }
     ]
    },
    {
     "title": "Process working set",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 8, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_working_set_bytes /1024/1024",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  }
 ]
}